### ISSUE TITLE
Test Kunde 999933 wirft einen Error

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/smart-order#15]
Der Kunde 999933 wirft den folgenden Error auf so-test

z.B: so-test &glncode=999933&basket=(2820210,1)
```
@400000005df61ac11c3e5ab4 play.api.UnexpectedException: Unexpected exception[NullPointerException: null]
@400000005df61ac11c3e5ab4 	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:276)
@400000005df61ac11c3f395c 	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:206)
@400000005df61ac11c3f3d44 	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
@400000005df61ac11c3f3d44 	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
@400000005df61ac11c3f412c 	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:98)
@400000005df61ac11c3f589c 	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
@400000005df61ac11c3f5c84 	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
@400000005df61ac11c3f606c 	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344)
@400000005df61ac11c3f606c 	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343)
@400000005df61ac11c3f7bc4 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
@400000005df61ac11c3f7fac Caused by: java.lang.NullPointerException: null
@400000005df61ac11c3f7fac 	at com.maxl.java.shared.NewUser.getPreferences(NewUser.java:49)
@400000005df61ac11c3f7fac 	at com.maxl.java.shared.NewUser.isPreferenceEmpty(NewUser.java:40)
@400000005df61ac11c3f8394 	at models.ShoppingRose.generateAlt(ShoppingRose.java:525)
@400000005df61ac11c3f9334 	at models.ShoppingRose.updateShoppingCart(ShoppingRose.java:703)
@400000005df61ac11c3f971c 	at controllers.MainController.getSmartBasket(MainController.java:241)
@400000005df61ac11c3f971c 	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$6$$anonfun$apply$6.apply(Routes.scala:215)
@400000005df61ac11c3f9b04 	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$6$$anonfun$apply$6.apply(Routes.scala:215)
@400000005df61ac11c3fa6bc 	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:157)
@400000005df61ac11c3faaa4 	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:156)
@400000005df61ac11c3faaa4 	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3$$anon$1.invocation(HandlerInvoker.scala:136)
```

mit Kunden_alle_NEU.csv

**Comment by zdavatz** [comment]
done with https://github.com/zdavatz/cpp2sqlite/issues/110
