### ISSUE TITLE
Exception caught in channelRead future

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/smart-order#90]
```
2020-07-03 15:18:20.259189500 [error] p.c.s.n.PlayRequestHandler - Exception caught in channelRead future
2020-07-03 15:18:20.259205500 java.util.concurrent.RejectedExecutionException: event executor terminated
2020-07-03 15:18:20.259214500 	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:715)
2020-07-03 15:18:20.259223500 	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:300)
2020-07-03 15:18:20.259231500 	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:691)
2020-07-03 15:18:20.259277500 	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:577)
2020-07-03 15:18:20.259286500 	at play.core.server.netty.PlayRequestHandler$$anonfun$channelRead$2$$anonfun$8.apply(PlayRequestHandler.scala:172)
2020-07-03 15:18:20.259294500 	at play.core.server.netty.PlayRequestHandler$$anonfun$channelRead$2$$anonfun$8.apply(PlayRequestHandler.scala:168)
2020-07-03 15:18:20.259307500 	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
2020-07-03 15:18:20.259315500 	at scala.util.Try$.apply(Try.scala:192)
2020-07-03 15:18:20.259323500 	at scala.util.Success.map(Try.scala:237)
2020-07-03 15:18:20.259331500 	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
2020-07-03 15:18:20.262996500 [error] i.n.u.c.D.rejectedExecution - Failed to submit a listener notification task. Event loop shut down?
2020-07-03 15:18:20.263007500 java.util.concurrent.RejectedExecutionException: event executor terminated
2020-07-03 15:18:20.263016500 	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:715)
2020-07-03 15:18:20.263024500 	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:300)
2020-07-03 15:18:20.263032500 	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:691)
2020-07-03 15:18:20.263050500 	at io.netty.util.concurrent.DefaultPromise.execute(DefaultPromise.java:674)
2020-07-03 15:18:20.263058500 	at io.netty.util.concurrent.DefaultPromise.notifyLateListener(DefaultPromise.java:644)
2020-07-03 15:18:20.263066500 	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:139)
2020-07-03 15:18:20.263075500 	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:93)
2020-07-03 15:18:20.263088500 	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:28)
2020-07-03 15:18:20.263096500 	at play.core.server.netty.PlayRequestHandler.play$core$server$netty$PlayRequestHandler$$sendSimpleErrorResponse(PlayRequestHandler.scala:287)
2020-07-03 15:18:20.263112500 	at play.core.server.netty.PlayRequestHandler$$anonfun$channelRead$2$$anonfun$apply$2.applyOrElse(PlayRequestHandler.scala:180)
```

**Comment by zdavatz** [comment]
This is related to a corrupt (to small) `swissmedic_packages.xlsx`. See https://github.com/zdavatz/cpp2sqlite/commit/8626bca0ac03f4486fa0dcf3b6daec680aea43b8
